# fly.toml app configuration file generated for getsideline on 2025-08-11T21:11:53+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'getsideline'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 1433

  [[services.ports]]
    port = 1433

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
